### ISSUE TITLE
Error pygame

### ISSUE THREAD

**Issue by unupingu** [guymcswain/N-est-Thermostat#2]
Hy.
I want to build your project but Im not so good in programing so i need some help with this error
Thanks 

-
![screenshot_2018-01-16-00-25-19](https://user-images.githubusercontent.com/24717851/34965458-71be9aca-fa54-11e7-9b61-907799b7c234.png)

**Comment by guymcswain** [comment]
I don't know why you are getting this message.  Have you tried other pygame demos or examples and do they run without error?

**Comment by unupingu** [comment]
Do you have .img of the project that you can send me?

**Comment by guymcswain** [comment]
I'm not sure what you mean by '.img'  The error you are seeing is an error in pygame initialization of the video subsystem.  It really has nothing to do with the application code that follows.

If you are asking for an image of the display produced this project, that is something I intend to post in the Wiki when I get the time.

You can also run this project on a pc (x86_64) to see the display.  Start the server in one terminal (node hvac_server.js)  then in another terminal run python thermostat.py.

**Comment by unupingu** [comment]
Ok thanks i will wait for the image

**Comment by guymcswain** [comment]
Screenshots posted.
